# Generated by Django 4.2 on 2023-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activty', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
